### ISSUE TITLE
bots create_bot

### ISSUE THREAD

**Issue by NeowuqiLee** [mMeijden/t3cpo#1]
strategy_list always return {"strategy_list": ["can't be blank", "is invalid"]}}
how pass the param 
[]  or
[{"strategy":"manual"}] 
are not work, even json.dumps() with it

**Comment by mMeijden** [comment]
Hi there,

The 3Commas documentation is a bit unclear about this, but the value should be a json array string.
for example: `'[{"strategy":"manual"}]'`

Here is an example that i used to create a bot.

```
resp = bot.Bots.create_bot(params={
    'name': 'test_bot',
    'account_id': 123456789, # random account id, change it with your account_id
    'pairs': ['BTC_LTC'], # sample pair
    'base_order_volume': 20,
    'take_profit': 1,
    'safety_order_volume': 40,
    'martingale_volume_coefficient': 1,
    'martingale_step_coefficient': 1,
    'max_safety_orders': 5,
    'active_safety_orders_count': 1,
    'safety_order_step_percentage': 1,
    'take_profit_type': 'total',
    'strategy_list': '[{"strategy":"manual"}]' # your strategy
})
```
Please let me know if this helps :)

**Comment by NeowuqiLee** [comment]
> Hi there,
> 
> The 3Commas documentation is a bit unclear about this, but the value should be a json array string.
> for example: `'[{"strategy":"manual"}]'`
> 
> Here is an example that i used to create a bot.
> 
> ```
> resp = bot.Bots.create_bot(params={
>     'name': 'test_bot',
>     'account_id': 123456789, # random account id, change it with your account_id
>     'pairs': ['BTC_LTC'], # sample pair
>     'base_order_volume': 20,
>     'take_profit': 1,
>     'safety_order_volume': 40,
>     'martingale_volume_coefficient': 1,
>     'martingale_step_coefficient': 1,
>     'max_safety_orders': 5,
>     'active_safety_orders_count': 1,
>     'safety_order_step_percentage': 1,
>     'take_profit_type': 'total',
>     'strategy_list': '[{"strategy":"manual"}]' # your strategy
> })
> ```
> 
> Please let me know if this helps :)



> Hi there,
> 
> The 3Commas documentation is a bit unclear about this, but the value should be a json array string.
> for example: `'[{"strategy":"manual"}]'`
> 
> Here is an example that i used to create a bot.
> 
> ```
> resp = bot.Bots.create_bot(params={
>     'name': 'test_bot',
>     'account_id': 123456789, # random account id, change it with your account_id
>     'pairs': ['BTC_LTC'], # sample pair
>     'base_order_volume': 20,
>     'take_profit': 1,
>     'safety_order_volume': 40,
>     'martingale_volume_coefficient': 1,
>     'martingale_step_coefficient': 1,
>     'max_safety_orders': 5,
>     'active_safety_orders_count': 1,
>     'safety_order_step_percentage': 1,
>     'take_profit_type': 'total',
>     'strategy_list': '[{"strategy":"manual"}]' # your strategy
> })
> ```
> 
> Please let me know if this helps :)

thank you, it worked

**Comment by NeowuqiLee** [comment]
no, it still returned
{"error": "record_invalid", "error_description": "Invalid parameters", "error_attributes": {"strategy_list": ["is invalid"]}}
I have solved by change the file api.py  **invoke** method, add json para
![image](https://user-images.githubusercontent.com/12151989/128672769-5f432d90-4ccc-44ed-8d4f-39a8ebad1b26.png)

**Comment by mMeijden** [comment]
Can you please send me your sample request code? I'm available to create a bot with the payload that i provided to you.

**Comment by NeowuqiLee** [comment]
> Can you please send me your sample request code? I'm available to create a bot with the payload that i provided to you.

  aa = {'name': ' 30740619-USDT_BNB', 'account_id': **xx**, 'strategy': 'long', 'pairs': ['USDT_BNB'],
              'base_order_volume': 50.0, 'safety_order_volume': 40.0, 'leverage_type': 'cross',
              'leverage_custom_value': 20, 'take_profit': 1.0, 'martingale_volume_coefficient': 1.1,
              'martingale_step_coefficient': 1.0, 'max_safety_orders': 10, 'active_safety_orders_count': 10,
              'safety_order_step_percentage': 1.0, 'take_profit_type': 'total',
              'strategy_list':'[{"strategy":"manual"}]'}
        res=self.bot.create_bot(aa)

**Comment by mMeijden** [comment]
I've deleted your comment as i think the bot name gave the account_id away and replaced it with xx
your comment was (anonymized):

> aa = {'name': ' xx-USDT_BNB', 'account_id': xx, 'strategy': 'long', 'pairs': ['USDT_BNB'],
'base_order_volume': 50.0, 'safety_order_volume': 40.0, 'leverage_type': 'cross',
'leverage_custom_value': 20, 'take_profit': 1.0, 'martingale_volume_coefficient': 1.1,
'martingale_step_coefficient': 1.0, 'max_safety_orders': 10, 'active_safety_orders_count': 10,
'safety_order_step_percentage': 1.0, 'take_profit_type': 'total',
'strategy_list':'[{"strategy":"manual"}]'}
res=self.bot.create_bot(aa)

I see you're referring to a self.bot. Can you please send me this sample code as well on how you're creating the bot and calling it?

As i've just created the bot with the sample you provided:
![image](https://user-images.githubusercontent.com/7498386/128677326-a56fbdc1-379c-4197-aadf-0985e5a62d41.png)
![image](https://user-images.githubusercontent.com/7498386/128677476-b8cc454b-db76-42d8-9da6-967ada1d4a48.png)


```
import t3cpo

bot = t3cpo.T3CPO(key='xx',
                  secret='xx')

aa = {
    'name': ' 30740629-USDT_BNB',
    'account_id': xx,
    'strategy': 'long',
    'pairs': ['USDT_BNB'],
    'base_order_volume': 50.0,
    'safety_order_volume': 40.0,
    'leverage_type': 'cross',
    'leverage_custom_value': 20,
    'take_profit': 1.0,
    'martingale_volume_coefficient': 1.1,
    'martingale_step_coefficient': 1.0,
    'max_safety_orders': 10,
    'active_safety_orders_count': 10,
    'safety_order_step_percentage': 1.0,
    'take_profit_type': 'total',
    'strategy_list': '[{"strategy":"manual"}]'
}

res = bot.Bots.create_bot(aa)
print(res)
```

Console output after invoking create_bot:
{'id': xx,
       'account_id': xx,
       'is_enabled': False,
       'max_safety_orders': 10,
       'active_safety_orders_count': 10,
       'pairs': ['USDT_BNB'],
       'strategy_list': [{'strategy': 'manual'}],
       'max_active_deals': 1,
       'active_deals_count': 0,
       'deletable?': True,
       'created_at': '2021-08-09T08:16:18.705Z',
       'updated_at': '2021-08-09T08:16:18.705Z',
       'trailing_enabled': None,
       'tsl_enabled': False,
       'deal_start_delay_seconds': None,
       'stop_loss_timeout_enabled': False,
       'stop_loss_timeout_in_seconds': 0,
       'disable_after_deals_count': None,
       'deals_counter': None,
       'allowed_deals_on_same_pair': None,
       'easy_form_supported': False,
       'close_deals_timeout': None,
       'url_secret': 'xx',
       'name': ' xx-USDT_BNB',
       'take_profit': '1.0',
       'base_order_volume': '50.0',
       'safety_order_volume': '40.0',
       'safety_order_step_percentage': '1.0',
       'take_profit_type': 'total',
       'type': 'Bot::SingleBot',
       'martingale_volume_coefficient': '1.1',
       'martingale_step_coefficient': '1.0',
       'stop_loss_percentage': '0.0',
       'cooldown': '0',
       'btc_price_limit': '0.0',
       'strategy': 'long',
       'min_volume_btc_24h': '0.0',
       'profit_currency': 'quote_currency',
       'min_price': None,
       'max_price': None,
       'stop_loss_type': 'stop_loss',
       'safety_order_volume_type': 'quote_currency',
       'base_order_volume_type': 'quote_currency',
       'account_name': 'Binance', 
       'trailing_deviation': '0.2',
       'finished_deals_profit_usd': '0.0',
       'finished_deals_count': '0',
       'leverage_type': 'cross',
       'leverage_custom_value': '20.0',
       'start_order_type': 'limit',
       'active_deals_usd_profit': '0.0'
       }

I also tried to create a bot with only the wrapper module, but i was able to create the bot again.
I really wish to help you but i simply cannot reproduce your issue.

**Comment by mMeijden** [comment]
I've deleted your comment as i think the bot name gave the account_id away and replaced it with xx
your comment was (anonymized):

> aa = {'name': ' xx-USDT_BNB', 'account_id': xx, 'strategy': 'long', 'pairs': ['USDT_BNB'],
'base_order_volume': 50.0, 'safety_order_volume': 40.0, 'leverage_type': 'cross',
'leverage_custom_value': 20, 'take_profit': 1.0, 'martingale_volume_coefficient': 1.1,
'martingale_step_coefficient': 1.0, 'max_safety_orders': 10, 'active_safety_orders_count': 10,
'safety_order_step_percentage': 1.0, 'take_profit_type': 'total',
'strategy_list':'[{"strategy":"manual"}]'}
res=self.bot.create_bot(aa)

I see you're referring to a self.bot. Can you please send me this sample code as well on how you're creating the bot and calling it?

As i've just created the bot with the sample you provided:
![image](https://user-images.githubusercontent.com/7498386/128677326-a56fbdc1-379c-4197-aadf-0985e5a62d41.png)
![image](https://user-images.githubusercontent.com/7498386/128677476-b8cc454b-db76-42d8-9da6-967ada1d4a48.png)


```
import t3cpo

bot = t3cpo.T3CPO(key='xx',
                  secret='xx')

aa = {
    'name': ' xx-USDT_BNB',
    'account_id': xx,
    'strategy': 'long',
    'pairs': ['USDT_BNB'],
    'base_order_volume': 50.0,
    'safety_order_volume': 40.0,
    'leverage_type': 'cross',
    'leverage_custom_value': 20,
    'take_profit': 1.0,
    'martingale_volume_coefficient': 1.1,
    'martingale_step_coefficient': 1.0,
    'max_safety_orders': 10,
    'active_safety_orders_count': 10,
    'safety_order_step_percentage': 1.0,
    'take_profit_type': 'total',
    'strategy_list': '[{"strategy":"manual"}]'
}

res = bot.Bots.create_bot(aa)
print(res)
```

Console output after invoking create_bot:
{'id': xx,
       'account_id': xx,
       'is_enabled': False,
       'max_safety_orders': 10,
       'active_safety_orders_count': 10,
       'pairs': ['USDT_BNB'],
       'strategy_list': [{'strategy': 'manual'}],
       'max_active_deals': 1,
       'active_deals_count': 0,
       'deletable?': True,
       'created_at': '2021-08-09T08:16:18.705Z',
       'updated_at': '2021-08-09T08:16:18.705Z',
       'trailing_enabled': None,
       'tsl_enabled': False,
       'deal_start_delay_seconds': None,
       'stop_loss_timeout_enabled': False,
       'stop_loss_timeout_in_seconds': 0,
       'disable_after_deals_count': None,
       'deals_counter': None,
       'allowed_deals_on_same_pair': None,
       'easy_form_supported': False,
       'close_deals_timeout': None,
       'url_secret': 'xx',
       'name': ' xx-USDT_BNB',
       'take_profit': '1.0',
       'base_order_volume': '50.0',
       'safety_order_volume': '40.0',
       'safety_order_step_percentage': '1.0',
       'take_profit_type': 'total',
       'type': 'Bot::SingleBot',
       'martingale_volume_coefficient': '1.1',
       'martingale_step_coefficient': '1.0',
       'stop_loss_percentage': '0.0',
       'cooldown': '0',
       'btc_price_limit': '0.0',
       'strategy': 'long',
       'min_volume_btc_24h': '0.0',
       'profit_currency': 'quote_currency',
       'min_price': None,
       'max_price': None,
       'stop_loss_type': 'stop_loss',
       'safety_order_volume_type': 'quote_currency',
       'base_order_volume_type': 'quote_currency',
       'account_name': 'Binance', 
       'trailing_deviation': '0.2',
       'finished_deals_profit_usd': '0.0',
       'finished_deals_count': '0',
       'leverage_type': 'cross',
       'leverage_custom_value': '20.0',
       'start_order_type': 'limit',
       'active_deals_usd_profit': '0.0'
       }

I also tried to create a bot with only the wrapper module, but i was able to create the bot again.
I really wish to help you but i simply cannot reproduce your issue.

**Comment by NeowuqiLee** [comment]
self.bot = T3CPO(KEY, SECRET).Bots

**Comment by NeowuqiLee** [comment]
![image](https://user-images.githubusercontent.com/12151989/128680095-1ff00cf4-76f5-4f24-95bd-4d5d806c31e2.png)
drive me mad
